### PR TITLE
WIP: Rsecon presentation "Bring your own classroom to a CodeRefinery workshop"

### LINKED ISSUE #24: RSECon talk - bring your own classroom to a CodeRefinery workshop
This got accepted 🎉 

Abstract: https://github.com/coderefinery/reports-and-proposals/blob/main/conference_abstracts/RSECon24_BYOC.md

### PR DESCRIPTION
**Pull request by samumantha**
RSECon presentation Tue 14 BST: https://virtual.oxfordabstracts.com/#/event/49081/submission/156

Preview: https://cicero.xyz/v3/remark/0.14.0/github.com/coderefinery/presentations/rsecon/2024-RSECon-BYOC.md/#1 

My three take-aways I want people to get from this:

- CodeRefinery exists and does workshops for all
- Anyone (in right timezone) can bring their own classroom
- We are open for ideas and suggestions for improvement

Some to-dos that currently come to mind: 

- [x] check use of .emph and *bold* 
- [x] slide numbers?
- [ ] ~lesson slide fixes (new image?)~
- [x] Experiences slides shortening or emphasize
- [ ] ~write out FAIR somewhere~
- [ ] generate pdf
- [ ] upload to Zenodo and add link
- [x] Update image credits slide
- [x] Test timing (10min) 
- [x] image sizes
- [x] anything more that we have learned?
- [x] Anything more under what is in it for you?
- [x] shorten
- [x] smaller font for quotes
- [x] update mastodon screenshot to something newer
- [x] logos fix (all on white background and in bottom?)
- [ ] ...

If you have a moment, please check and add comments :) 

Resolves #24

### CODE REVIEW

**Comment by bast** [comment]
I will improve the font(s).

**Comment by bast** [comment]
Hopefully it's better now but I can change it more.

**Comment by bast** [comment]
One more thing we learned: the more people participate, the harder it is to communicate changes (example: changes in second week format).

**Comment by samumantha** [comment]
Any good suggestion what could still be left out? 😉

**Comment by bast** [comment]
> Any good suggestion what could still be left out? 😉

Last two slides could be collapsed into one and instead of listing all these places where we are it could list one entry point (QR code?) from which one can find all those places?

**Comment by samumantha** [comment]
Major rearrangement and shortening, focus on BYOC
ToDO: 
- [x] new image for Problem slide
- [x] Remove unnecessary stuff from how you can join slide ~(maybe remove whole slide)~
- [x] add contact details

**Comment by samumantha** [comment]
Now ready for final review :)

**Comment by bast** [comment]
I would only change the "The format is new and confusing" - sounds like we are creating something confusing.

Maybe "The format is unusual and requires some getting used to"?

**Comment by samumantha** [comment]
Hmm, something changed in the lesson slide at some point, that I didn't notice up till now.

~Could something in the css be adjusted to fit the lesson titles up top and the second header there on full width while not moving it further down?~

**Review by samumantha — COMMENTED** [review]
Last fixes

**Comment by bast** [comment]
Building pdf ...

**Comment by bast** [comment]
[presentation.pdf](https://github.com/user-attachments/files/16835007/presentation.pdf)

**Comment by samumantha** [comment]
Thank you! 
Sqashmerging this now.

**Pull request merged**
