### PR TITLE
Color to new images and lesson screenshot split

### PR DESCRIPTION
**Pull request by samumantha**
Related to RSECon presentation

- color to new graphics
- split lesson screenshot into 2 for readability

@bast

### CODE REVIEW

**Comment by bast** [comment]
Looks great! Not sure why we have both png and svg. I think just svg will work fine.

**Comment by samumantha** [comment]
Hmm, good point I thought pngs may be safer to have that's why I exported them as well

**Comment by bast** [comment]
It's not a problem and probably practical to have them there too.

**Comment by samumantha** [comment]
Does it matter for pdf generation from the html if we have png or svg?

**Comment by samumantha** [comment]
Hmm something is still off with the first screenshot, how can it best be fit on the slide?

**Comment by bast** [comment]
Looking ...

**Comment by bast** [comment]
Maybe better now - hoping I was fixing the right slide.

**Comment by bast** [comment]
It's perfect.

**Pull request merged**
