### PR TITLE
Rsecon presentation

### PR DESCRIPTION
**Pull request by samumantha**
Open discussion points and to do marked in text with TODO

### CODE REVIEW

**Comment by samumantha** [comment]
General:
- [x] reduce text
- [x] improve story -> use slide titles
- [x] fix formatting
- [x] fill in statistics numbers
- [x] check for consistency
- [x] check text for typos and grammar
- [x] Bulletpoints all start with uppercase?
- [x] slide numbers?
- [x] References and Collaborators
- [x] emphasize main takeaway lesson
- [x] NordicRSE advertisement? -> unconference dates and ongoing efforts?
- [x] slide about next workshop
- [ ] upload to Zenodo
- [x] add license information about images and text
- [x] all images have alt text
- [x] Improve slide "Collaboration across borders", consider using map
- [x] Consider splitting CR overview slide into "what is CR" and "what we do"
- [x] Presenter notes for lesson slide: Sphinx format with all markdown, no slides, multi-collaborator effort, built around exercises, minimum one larger exercise per lesson, solutions in dropdown, discussion suggestions, instructor guide, making things citable is WIP, ...

**Comment by samumantha** [comment]
Should we split the CR overview slide into "what is CR" and "what we do"? Don't know if there is enough separate stuff though...

**Comment by samumantha** [comment]
**RB: done**

Course portfolio: Rater than lesson titles we could show lesson topics as questions a researcher may have along the journey of writing research code? Some kind of visual would be nice ... But if it is only text maybe not handwritten would be better :thinking:

**Comment by samumantha** [comment]
Presenternotes for lesson slide:  Sphinx format with all markdown, no slides, multi-collaborator effort, built around exercises, minimum one larger exercise per lesson, solutions in dropdown, discussion suggestions, instructor guide, making things citable is WIP, ...

**Comment by samumantha** [comment]
Workshop setup: 
- remove survey? ; 
- add possible post hackathon ?; 
- add instructor onboarding (screenshare, lesson prep,...); 
- add writing retreat ?
- add recordings ?
- somehow tell the story on how this evolved? Maybe one more slide? 

->**done**

**Comment by samumantha** [comment]
Participating as learner slide:

Is helper role up to date?
Where t o put satellite events?
Does individuals in team (zoom vs in-person) need clarification?

-> **done**

**Comment by samumantha** [comment]
Bring your own classroom: image to be created

Not separate but included into new exercise options slide -> **done**

**Comment by samumantha** [comment]
**RB working on it**

Workshop stats:
TODO: fill in number of workshops

**Comment by samumantha** [comment]
Collaboration across borders: add map where teachers are from? If there is time... not necessary.
Do we have the data already somewhere ready?

Only if there is time to do so, not critical

**Comment by samumantha** [comment]
**RB: done**

What we have learned slide: What do we want to communicate? Only workshops or CR project in general?

**Comment by samumantha** [comment]
**RB: done**

Future slide: 
TODO: check if  these are up to date
TODO: How would we want collaboration with similar projects to look like?
TODO: Future of our workshops vs future of coderefinery, separate or focus on one?

**Comment by samumantha** [comment]
**RB: done**

News: mention about weekly toots?

**Comment by samumantha** [comment]
**RB: done**, but we can decide to modify or combine to one slide/animation

Collaborative doc slide:
TODO: show this slide as screenshot from collaborative doc, info, questions and poll, maybe as small slide by slide animation?

TODO: Example text to copy to hedgedoc:

```
  ## Exercise: recording changes

  https://coderefinery.github.io/git-intro/basics/#exercise-record-changes

  :::info

      Until xx:10, after that break until xx:20
      Goal: introduce two new changes, experiment with "git diff", and commit the two changes separately
      There are optional exercise below :::

  Questions about exercises continue here:

  - What is the difference between git branch <branch-name> and git checkout -b <branch-name>? Are they the same or is it a good practice to favor one over the other?

      - the first makes branch but doesn't switch to it. the second makes+switches. Depends on what you need, I use both in different cases.
      - The checkout command can be used to checkout an arbitrary commit without switching branch. But in this use-case they do the same thing.
      - To add to the options there is also git switch -c branch_name ('-c' for "create")... Focus on getting proficient with one option.


  How is the speed so far for all (add an "o")?

      too fast: oooooooO
      too slow:
      just right: ooo
      not sure what I should do now:
      need a break soon (we will take breaks):
      Speed is good but I know most of it already so far: ooooooo
```

**Comment by samumantha** [comment]
Does this look ok? Something to add/remove?

**Comment by samumantha** [comment]
Was thinking a bit about the setup of the how to participate slide. Would this make it better or worse? 
Maybe upside down of left to right? Or just leave the old circular one? 

Idea was to emphasize more what is the same for everyone and what is different.

**Comment by bast** [comment]
- pre/post: it's perfect
- how to participate: I think it is better than before - new version is good as is

**Comment by bast** [comment]
**RB  working on it**

Add slide where we acknowledge people and orgs and also provide license/copyright info. We can jump over the slide when presenting.

**Comment by bast** [comment]
I have collected remaining tasks on topmost checklist since I was losing overview. Working on those.

**Comment by bast** [comment]
Merging. Remaining:
- careful read
- cosmetics
- Zenodo upload

**Pull request merged**
